default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: 'myapp'
  password: 'password1'
  host: 'localhost'
  database: liam_ebook_development

test:
  <<: *default
  username: 'myapp'
  password: 'password1'
  host: 'localhost'
  database: liam_ebook_test

production:
  <<: *default
  database: liam_ebook_production
