# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 934f13947259c82699b731085f40e9d0f7485c3e8fe0c1aade8821ea4cd247044c38fed2521c0ac635bbd0c6d251d478a8a0952a2af53b318bf706ba6446bcef
  pdf_url: 'https://s3-eu-west-1.amazonaws.com/liam-staging/guide.pdf'
  admin_username: 'liam'
  admin_password: 'gains'
  from_email: 'from@example.com'

test:
  secret_key_base: d15e5167455e9391cec803a810c3a5f61f907e865b5ed33e01e7eeec645db87592de6a4cefb290096541d35bbded47a5dd598c7b56f0c117a7df2585a8dd76d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  pdf_url: <%= ENV['PDF_URL'] %>
  admin_username: <%= ENV['ADMIN_USERNAME'] %>
  admin_password: <%= ENV['ADMIN_PASSWORD'] %>
  from_email: <%= ENV['FROM_EMAIL'] %>
